name: Sync main to branches

on:
    push:
        branches:
            - main

jobs:
    create-pull-requests:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Git
              run: |
                  git config --global user.name 'GitHub Action'
                  git config --global user.email 'action@github.com'

            - name: Fetch all branches
              run: git fetch --all

            - name: List branches
              id: list-branches
              run: |
                  git branch -r | grep -v '\->' | grep -v 'main' | awk '{print $1}' | sed 's/origin\///' > branches.txt
                  echo "::set-output name=branches::$(cat branches.txt | tr '\n' ' ')"

            - name: Create pull requests
              run: |
                  branches=$(echo "${{ steps.list-branches.outputs.branches }}" | tr ' ' '\n')
                  for branch in $branches; do
                    git checkout main
                    git pull origin main
                    git checkout -b sync/main-to-$branch
                    git pull origin $branch || true
                    git merge main --no-commit --no-ff
                    if [[ `git status --porcelain` ]]; then
                      git commit -m 'Sync from main'
                      git push origin sync/main-to-$branch
                      gh pr create --title "Sync main to $branch" --body "This PR syncs changes from main to the $branch branch." --head sync/main-to-$branch --base $branch
                    else
                      echo "No changes to commit for branch $branch"
                    fi
                  done
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
